import { type KnowledgeEntry } from "./knowledge.types";

export const SUPPORT_EMAIL = "support@novagear.com";
export const SUPPORT_HOURS = "Monday to Friday, 9am to 6pm EST";
export const FREE_SHIPPING_THRESHOLD = "$50";
export const RETURN_WINDOW_DAYS = 30;

export const KNOWLEDGE_BASE: KnowledgeEntry[] = [
  {
    id: "shipping-domestic-options",
    category: "shipping",
    question: "What domestic shipping options and costs are available?",
    answer:
      "Within the US we offer Standard shipping (3 to 5 business days, $4.95) and Express shipping (1 to 2 business days, $14.95). Orders of $50 or more ship free with Standard shipping.",
    keywords: [
      "shipping",
      "delivery",
      "how long",
      "arrive",
      "standard",
      "express",
      "cost",
      "shipping fee",
      "free shipping",
      "domestic",
    ],
  },
  {
    id: "shipping-international",
    category: "shipping",
    question: "Do you ship internationally and how long does it take?",
    answer:
      "Yes, we ship to over 25 countries. International orders arrive in 7 to 14 business days and shipping is calculated at checkout based on destination. Customers are responsible for any import duties or customs fees charged on arrival.",
    keywords: [
      "international",
      "overseas",
      "abroad",
      "country",
      "customs",
      "duties",
      "import",
      "worldwide",
      "outside us",
    ],
  },
  {
    id: "shipping-processing-time",
    category: "shipping",
    question: "How long before my order ships?",
    answer:
      "Orders are processed and dispatched within 1 business day. Orders placed on weekends or US public holidays are processed the next business day. You will receive a tracking link by email once your order ships.",
    keywords: [
      "process",
      "processing",
      "dispatch",
      "ship out",
      "when ship",
      "handling time",
      "tracking",
    ],
  },
  {
    id: "returns-policy",
    category: "returns",
    question: "What is your return policy?",
    answer:
      "You can return unused items in their original packaging within 30 days of delivery for a full refund. Start a return by emailing support@novagear.com with your order number. Return shipping is free for orders within the US.",
    keywords: [
      "return",
      "send back",
      "return policy",
      "give back",
      "unused",
      "30 days",
      "money back",
    ],
  },
  {
    id: "returns-refund-timing",
    category: "returns",
    question: "How long do refunds take?",
    answer:
      "Once we receive and inspect your returned item, refunds are issued to your original payment method within 5 to 7 business days. We will email you when the refund is processed.",
    keywords: [
      "refund",
      "refunded",
      "money back",
      "how long refund",
      "refund time",
      "reimburse",
    ],
  },
  {
    id: "returns-exchanges",
    category: "returns",
    question: "Can I exchange an item for a different size or color?",
    answer:
      "Yes. For an exchange, email support@novagear.com with your order number and the size or color you would like. Exchanges follow the same 30-day window as returns and are subject to availability.",
    keywords: [
      "exchange",
      "swap",
      "different size",
      "different color",
      "wrong size",
      "replace size",
    ],
  },
  {
    id: "warranty-coverage",
    category: "warranty",
    question: "What does your warranty cover?",
    answer:
      "Every Nova Gear product includes a 1-year limited warranty covering defects in materials and workmanship. It does not cover accidental damage or normal wear and tear. To file a claim, email support@novagear.com with your order number and a photo of the issue.",
    keywords: [
      "warranty",
      "guarantee",
      "defect",
      "defective",
      "broken",
      "faulty",
      "claim",
      "repair",
      "damaged",
    ],
  },
  {
    id: "payments-methods",
    category: "payments",
    question: "What payment methods do you accept?",
    answer:
      "We accept Visa, Mastercard, and American Express, plus PayPal, Apple Pay, and Google Pay. All payments are processed over an encrypted, PCI-compliant connection.",
    keywords: [
      "payment",
      "pay",
      "credit card",
      "debit",
      "visa",
      "mastercard",
      "amex",
      "paypal",
      "apple pay",
      "google pay",
      "checkout",
    ],
  },
  {
    id: "payments-security",
    category: "payments",
    question: "Is my payment information secure?",
    answer:
      "Yes. We never store full card numbers on our servers. Payments are handled by a PCI-compliant processor over an encrypted connection, so your card details stay protected.",
    keywords: [
      "secure",
      "security",
      "safe",
      "encrypted",
      "card stored",
      "data safe",
      "pci",
    ],
  },
  {
    id: "orders-tracking",
    category: "orders",
    question: "How do I track my order?",
    answer:
      "When your order ships you will receive an email with a tracking link. You can follow that link any time to see the latest delivery status.",
    keywords: [
      "track",
      "tracking",
      "where is my order",
      "order status",
      "delivery status",
      "find order",
    ],
  },
  {
    id: "orders-change-cancel",
    category: "orders",
    question: "Can I change or cancel my order after placing it?",
    answer:
      "We can change or cancel an order within 1 hour of it being placed, before it enters fulfillment. Email support@novagear.com as soon as possible with your order number. After that window the order is on its way and can be handled as a return once it arrives.",
    keywords: [
      "cancel",
      "change order",
      "modify",
      "edit order",
      "update address",
      "wrong address",
      "mistake",
    ],
  },
  {
    id: "support-contact-hours",
    category: "support",
    question: "How can I contact support and when are you open?",
    answer:
      "You can reach our team at support@novagear.com. Live support is available Monday to Friday, 9am to 6pm EST, and we aim to answer every email within 24 hours, including over the weekend.",
    keywords: [
      "contact",
      "support",
      "help",
      "reach",
      "hours",
      "open",
      "email",
      "phone",
      "talk to someone",
      "human",
      "agent",
    ],
  },
  {
    id: "products-catalog-overview",
    category: "products",
    question: "What do you sell / what kind of products do you offer?",
    answer:
      "Nova Gear makes outdoor and tech accessories built to last. Our lineup covers four areas: **Packs & bags** (like the Trailhead 30L Pack), **Lighting** (the Summit Headlamp), **Apparel** (the Ridgeline Shell), and **Tech** (the Pulse Portable Speaker and the Volt 20K Power Bank). Ask about any category or product and I'll give you the details.",
    keywords: [
      "what do you sell",
      "products",
      "product",
      "catalog",
      "catalogue",
      "range",
      "lineup",
      "offer",
      "sell",
      "buy",
      "shop",
      "store",
      "items",
      "inventory",
      "categories",
      "what do you have",
    ],
  },
  {
    id: "products-trailhead-pack",
    category: "products",
    question: "Tell me about the Trailhead 30L Pack.",
    answer:
      "The Trailhead 30L Pack ($129) is our bestselling daypack — a 30-litre weatherproof pack with a padded laptop sleeve, hip-belt support, and a lifetime-stitching guarantee. Great for day hikes, commuting, and travel.",
    keywords: [
      "trailhead",
      "pack",
      "backpack",
      "daypack",
      "bag",
      "30l",
      "packs",
      "bags",
      "rucksack",
      "luggage",
    ],
  },
  {
    id: "products-summit-headlamp",
    category: "products",
    question: "Tell me about the Summit Headlamp.",
    answer:
      "The Summit Headlamp ($69) puts out 500 lumens with a USB-C rechargeable battery, a red night-mode, and an IPX6 water-resistant rating. It runs up to 40 hours on a charge — built for trails, camping, and power outages.",
    keywords: [
      "summit",
      "headlamp",
      "light",
      "lamp",
      "torch",
      "flashlight",
      "lighting",
      "lumens",
      "headlight",
    ],
  },
  {
    id: "products-ridgeline-shell",
    category: "products",
    question: "Tell me about the Ridgeline Shell.",
    answer:
      "The Ridgeline Shell ($189) is a 3-layer waterproof, breathable hardshell jacket with pit-zip venting and a helmet-compatible hood. Fully seam-sealed for serious weather. Available in S–XXL.",
    keywords: [
      "ridgeline",
      "shell",
      "jacket",
      "coat",
      "apparel",
      "clothing",
      "waterproof",
      "raincoat",
      "outerwear",
    ],
  },
  {
    id: "products-pulse-speaker",
    category: "products",
    question: "Tell me about the Pulse Portable Speaker.",
    answer:
      "The Pulse Portable Speaker ($59) is a pocket-sized Bluetooth 5.3 speaker with 12 hours of playback, an IP67 waterproof-and-dustproof rating, and a built-in mic for calls. You can pair two of them for stereo sound.",
    keywords: [
      "pulse",
      "speaker",
      "speakers",
      "portable speaker",
      "bluetooth",
      "audio",
      "sound",
      "music",
      "tech",
      "gadget",
      "electronics",
    ],
  },
  {
    id: "products-volt-power-bank",
    category: "products",
    question: "Tell me about the Volt 20K Power Bank.",
    answer:
      "The Volt 20K Power Bank ($49) is a 20,000mAh battery with 30W USB-C fast charging and two ports, so it charges a phone roughly four times or a laptop once. Airline carry-on safe.",
    keywords: [
      "volt",
      "power bank",
      "powerbank",
      "battery",
      "charger",
      "charging",
      "portable charger",
      "tech",
      "gadget",
      "electronics",
      "usb",
    ],
  },
  {
    id: "products-how-to-order",
    category: "products",
    question: "How do I buy or order a product?",
    answer:
      "You can browse and order any product on the Nova Gear website at novagear.com. Add what you'd like to your cart and check out — orders over $50 ship free. I can't place an order for you from chat, but I'm happy to help you pick the right product or answer questions before you buy.",
    keywords: [
      "order",
      "buy",
      "purchase",
      "place order",
      "checkout",
      "add to cart",
      "how to buy",
      "how to order",
      "website",
      "link",
      "url",
    ],
  },
  {
    id: "policies-privacy",
    category: "policies",
    question: "What is your privacy policy / how is my data handled?",
    answer:
      "We collect only what we need to process your order — name, contact, shipping address, and order details — and we never sell your personal data. Payment details are handled by a PCI-compliant processor, not stored on our servers. You can ask us to access or delete your data any time by emailing support@novagear.com. Full policy: novagear.com/privacy.",
    keywords: [
      "privacy",
      "privacy policy",
      "data",
      "personal data",
      "gdpr",
      "my information",
      "data protection",
      "delete my data",
      "tracking",
      "cookies",
    ],
  },
  {
    id: "policies-terms",
    category: "policies",
    question: "What are your terms and conditions?",
    answer:
      "Our terms cover how you use the Nova Gear site and buy from us: prices and availability can change, orders are confirmed once payment clears, and our returns, warranty, and shipping policies form part of the agreement. Promotions can't be combined unless stated. The full terms are at novagear.com/terms — ask me about any specific point and I'll explain it.",
    keywords: [
      "terms",
      "conditions",
      "terms and conditions",
      "tos",
      "terms of service",
      "agreement",
      "legal",
      "fine print",
      "rules",
    ],
  },
  {
    id: "policies-cancellation",
    category: "policies",
    question: "What is your order cancellation policy?",
    answer:
      "You can cancel an order within 1 hour of placing it, before it enters fulfillment — just email support@novagear.com with your order number. After that the order is on its way and is handled as a return once it arrives. Refunds for cancelled orders go back to your original payment method within 5 to 7 business days.",
    keywords: [
      "cancellation",
      "cancellation policy",
      "cancel order",
      "cancel my order",
      "stop order",
      "void order",
      "order policy",
    ],
  },
];
